### PR TITLE
Update CSS and header to 2019

### PR DESCRIPTION
**Pull request by boaz0**

### CODE REVIEW

**Comment by AmitAronovitch** [comment]
navbar titles should be changed:
TIMELINE->HOME (or MESSAGES or TOP, not sure...)
FAQ -> Accessibility

Also it is not usable for navigating back to HOME, as it is disappears once you push any other option - maybe make it fixed-position (but we may leave that for next PR)

**Comment by AmitAronovitch** [comment]
the save-the-dates part is missing - site needs to contain all known info (when is Django Girls? When is the Workshops)

**Comment by AmitAronovitch** [comment]
resolves #15

**Comment by boaz0** [comment]
@AmitAronovitch waiting on your review

**Pull request merged**
